name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Builds - build Flutter APK and create github release
    steps:
      - uses: Dank-del/flutter-build-and-publish-action@v1
